### ISSUE TITLE
component-centric-snapshot-description-active-inactive-term-match rules do not consider languageCode

### ISSUE THREAD

**Issue by danka74** [IHTSDO/release-validation-framework#31]
Dear SNOMED,

these rules do not consider languageCode when comparing descriptions, led to a false positive when correcting terms which were previousle assigned the wrong languageCode.

E.g. after row 69 add a.languageCode = b.languageCode

https://github.com/IHTSDO/release-validation-framework/blob/e7c1b6061ca3a7c6ace0e611fc6a5f72ef592d70/importer/src/main/resources/scripts/component-centric/component-centric-snapshot-description-active-inactive-term-match-authoring.sql
https://github.com/IHTSDO/release-validation-framework/blob/e7c1b6061ca3a7c6ace0e611fc6a5f72ef592d70/importer/src/main/resources/scripts/component-centric/component-centric-snapshot-description-active-inactive-term-match.sql

**Comment by CoderMChu** [comment]
Hi Daniel,

Thanks for reporting the issue above. We have fixed this and it will be included in the next RVF release (2.2.0).
Thanks
Michael

**Comment by CoderMChu** [comment]
MAINT-701 is created to track this.
