### ISSUE TITLE
Docker "quickstart" instructions don't work

### ISSUE THREAD

**Issue by abelardy** [IHTSDO/release-validation-framework#33]
Using Ubuntu 18.04.4 LTS.

Done:
  sudo snap install docker
  (docker 19.03.11 from Canonical✓ installed)
  sudo apt install git

and then
  git clone https://github.com/IHTSDO/release-validation-framework.git
  cd release-validation-framework
  docker-compose up -d

but get
ERROR: Couldn't connect to Docker daemon - you might need to run `docker-machine start default`.

so tried
docker-machine start default

and got
Docker machine "default" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.

..at which point, not knowing much about what "docker" even is or does, and not wanting to RTFM, I came here to blow off steam.

**Comment by rorydavidson** [comment]
@abelardy This looks an issue with your installation of docker/ubuntu, but it might work if you try to use sudo:
`sudo docker-compose up -d`

**Comment by abelardy** [comment]
Thanks Rory...`sudo docker-compose up -d` seemed to work. But if I open a web browser on [http://localhost:8081/api/swagger-ui.html](url) it looks like the server isn't actually started. 

I tried running the enticing looking `start-api-local.sh` but that appears to need maven installing, which wasn't mentioned in the quick start guide. I shall see if that helps...

**Comment by rorydavidson** [comment]
@abelardy if you want to hold on a little, we are in the process of tweaking the documentation and docker images so that they should work more _smoothly_

**Comment by abelardy** [comment]
Thx Rory. I guess you won't be surprised to know that installing maven and then trying the start-api-local shell script didn't work either! Bailed with compile errors.

**Comment by abelardy** [comment]
Works now (20200918)

Successful build over minimal installation of Ubuntu 20.04.1 LTS as follows:

sudo apt install mysql-server
sudo mysql_secure_installation
sudo mysql
	ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'Slartibartfast';
	FLUSH PRIVILEGES;
	exit
sudo systemctl status mysql.service

sudo apt install git
sudo apt install docker                  # may not be necessary? Certainly not sufficient....
sudo apt install docker-compose
git clone https://github.com/IHTSDO/release-validation-framework.git
cd release-validation-framework
sudo docker-compose up -d 		# to compile

To run:
sudo docker-compose up -d		

Wait a couple of minutes, then open firefox and browse http://localhost:8081/api/swagger-ui.html

**Comment by abelardy** [comment]
Works now (20200918). Successful build over minimal install of Ubuntu 18.04.1 LTS in VirtualBox, as follows:

sudo apt install mysql-server
sudo mysql_secure_installation
sudo mysql
	ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
	FLUSH PRIVILEGES;
	exit

sudo systemctl status mysql.service

sudo apt install git
sudo apt install docker
sudo apt install docker-compose
git clone https://github.com/IHTSDO/release-validation-framework.git
cd release-validation-framework
sudo docker-compose up -d 		# to compile

To run:
sudo docker-compose up -d		

Wait a couple of minutes, then open firefox and browse http://localhost:8081/api/swagger-ui.html

**Comment by rorydavidson** [comment]
@abelardy good to hear it's working now, thanks. 

However, when using the docker containers, there is no need to install MYSQL, it is run as a docker container alongside the rvf container. You only need the commands from installing git onwards.
