### ISSUE TITLE
Doesn't compile with JDK 11

### ISSUE THREAD

**Issue by abelardy** [IHTSDO/release-validation-framework#34]
Using Ubuntu 18.04.4 LTS.
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)

Done:
  sudo apt install maven

Get
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 11.0.7, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "5.3.0-62-generic", arch: "amd64", family: "unix"

Tried
 cd ~/release-validation-framework
 mvn clean install

Get

[INFO] Changes detected - recompiling the module!
[INFO] Compiling 12 source files to /home/iresuser/release-validation-framework/model/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/iresuser/release-validation-framework/model/src/main/java/org/ihtsdo/rvf/entity/Assertion.java:[13,33] package javax.xml.bind.annotation does not exist
[ERROR] /home/iresuser/release-validation-framework/model/src/main/java/org/ihtsdo/rvf/entity/Assertion.java:[14,33] package javax.xml.bind.annotation does not exist
[ERROR] /home/iresuser/release-validation-framework/model/src/main/java/org/ihtsdo/rvf/entity/Assertion.java:[24,2] cannot find symbol
  symbol: class XmlRootElement
[ERROR] /home/iresuser/release-validation-framework/model/src/main/java/org/ihtsdo/rvf/entity/Assertion.java:[62,10] cannot find symbol
  symbol:   class XmlElement
  location: class org.ihtsdo.rvf.entity.Assertion
[ERROR] /home/iresuser/release-validation-framework/model/src/main/java/org/ihtsdo/rvf/entity/Assertion.java:[71,10] cannot find symbol
  symbol:   class XmlElement
  location: class org.ihtsdo.rvf.entity.Assertion
[ERROR] /home/iresuser/release-validation-framework/model/src/main/java/org/ihtsdo/rvf/entity/Assertion.java:[88,10] cannot find symbol
  symbol:   class XmlElement
  location: class org.ihtsdo.rvf.entity.Assertion
[ERROR] /home/iresuser/release-validation-framework/model/src/main/java/org/ihtsdo/rvf/entity/Assertion.java:[97,10] cannot find symbol
  symbol:   class XmlElement
  location: class org.ihtsdo.rvf.entity.Assertion
[INFO] 7 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for SNOMED Release Validation Framework 2.8.0:
[INFO] 
[INFO] SNOMED Release Validation Framework ................ SUCCESS [01:33 min]
[INFO] model .............................................. FAILURE [  8.834 s]
[INFO] data-service ....................................... SKIPPED
[INFO] validation-service ................................. SKIPPED
[INFO] importer ........................................... SKIPPED
[INFO] execution-service .................................. SKIPPED
[INFO] api ................................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:57 min
[INFO] Finished at: 2020-07-17T15:40:12+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project model: Compilation failure: Compilation failure: 
[ERROR] /home/iresuser/release-validation-framework/model/src/main/java/org/ihtsdo/rvf/entity/Assertion.java:[13,33] package javax.xml.bind.annotation does not exist
[ERROR] /home/iresuser/release-validation-framework/model/src/main/java/org/ihtsdo/rvf/entity/Assertion.java:[14,33] package javax.xml.bind.annotation does not exist
[ERROR] /home/iresuser/release-validation-framework/model/src/main/java/org/ihtsdo/rvf/entity/Assertion.java:[24,2] cannot find symbol
[ERROR]   symbol: class XmlRootElement
[ERROR] /home/iresuser/release-validation-framework/model/src/main/java/org/ihtsdo/rvf/entity/Assertion.java:[62,10] cannot find symbol
[ERROR]   symbol:   class XmlElement
[ERROR]   location: class org.ihtsdo.rvf.entity.Assertion
[ERROR] /home/iresuser/release-validation-framework/model/src/main/java/org/ihtsdo/rvf/entity/Assertion.java:[71,10] cannot find symbol
[ERROR]   symbol:   class XmlElement
[ERROR]   location: class org.ihtsdo.rvf.entity.Assertion
[ERROR] /home/iresuser/release-validation-framework/model/src/main/java/org/ihtsdo/rvf/entity/Assertion.java:[88,10] cannot find symbol
[ERROR]   symbol:   class XmlElement
[ERROR]   location: class org.ihtsdo.rvf.entity.Assertion
[ERROR] /home/iresuser/release-validation-framework/model/src/main/java/org/ihtsdo/rvf/entity/Assertion.java:[97,10] cannot find symbol
[ERROR]   symbol:   class XmlElement
[ERROR]   location: class org.ihtsdo.rvf.entity.Assertion
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :model

**Comment by kaicode** [comment]
Hi @abelardy, please compile this project with JDK 1.8
https://github.com/IHTSDO/release-validation-framework/blob/master/pom.xml#L17
Cheers,
Kai Kewley
