### ISSUE TITLE
Docker-compose is out of date

### ISSUE THREAD

**Issue by edeati** [IHTSDO/release-validation-framework#57]
Hi,
There was a change lately to update mysql from 5.7 to 8.0.28 (commit b9f775d00d836b6e5c1c606558c9d34c9b6f99a9)  and now the docker server startup dies with `java.util.concurrent.ExecutionException: java.sql.SQLSyntaxErrorException: The used command is not allowed with this MySQL version`

Can you please update docker-compose.yml to use mysql 8.0.28?

**Comment by edeati** [comment]
Just another note `local_infile=1;` needs to be set for the new Mysql DB image to be able to import the RF2 zip files

**Comment by CoderMChu** [comment]
@edeati This issue has been fixed in 6.4.2 release. I will close this for now. Any issue please let me know. Thanks.
